"""
The curated source list. Adding a source is adding a line; the labels are
part of the data and shown next to every story. Tiers and ownership are
editorial judgements — keep them justified and conservative.
"""

from __future__ import annotations

from argus.domain.news import NewsCategory, NewsSource, Ownership

W, D, C, R = NewsCategory.WORLD, NewsCategory.DEFENSE, NewsCategory.CYBER, NewsCategory.REGIONAL
PRIV, PUB, STATE, IGO = (
    Ownership.PRIVATE,
    Ownership.PUBLIC,
    Ownership.STATE,
    Ownership.INTERGOVERNMENTAL,
)


def _source(
    id: str,
    name: str,
    feed: str,
    home: str,
    category: NewsCategory,
    tier: int,
    ownership: Ownership,
    country: str | None,
) -> NewsSource:
    return NewsSource(
        id=id,
        name=name,
        feed_url=feed,
        homepage=home,
        category=category,
        tier=tier,
        ownership=ownership,
        country=country,
    )


DEFAULT_SOURCES: tuple[NewsSource, ...] = (
    _source(
        "bbc",
        "BBC News",
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "https://www.bbc.com/news/world",
        W,
        1,
        PUB,
        "GB",
    ),
    _source(
        "dw",
        "Deutsche Welle",
        "https://rss.dw.com/rdf/rss-en-all",
        "https://www.dw.com/en",
        W,
        1,
        PUB,
        "DE",
    ),
    _source(
        "france24",
        "France 24",
        "https://www.france24.com/en/rss",
        "https://www.france24.com/en",
        W,
        1,
        PUB,
        "FR",
    ),
    _source(
        "npr",
        "NPR",
        "https://feeds.npr.org/1004/rss.xml",
        "https://www.npr.org/sections/world",
        W,
        1,
        PUB,
        "US",
    ),
    _source(
        "guardian",
        "The Guardian",
        "https://www.theguardian.com/world/rss",
        "https://www.theguardian.com/world",
        W,
        1,
        PRIV,
        "GB",
    ),
    _source(
        "un-news",
        "UN News",
        "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        "https://news.un.org",
        W,
        1,
        IGO,
        None,
    ),
    _source(
        "aljazeera",
        "Al Jazeera",
        "https://www.aljazeera.com/xml/rss/all.xml",
        "https://www.aljazeera.com",
        W,
        2,
        STATE,
        "QA",
    ),
    _source(
        "kyiv-independent",
        "The Kyiv Independent",
        "https://kyivindependent.com/news-archive/rss/",
        "https://kyivindependent.com",
        R,
        2,
        PRIV,
        "UA",
    ),
    _source("tass", "TASS", "https://tass.com/rss/v2.xml", "https://tass.com", W, 3, STATE, "RU"),
    _source(
        "defense-news",
        "Defense News",
        "https://www.defensenews.com/arc/outboundfeeds/rss/",
        "https://www.defensenews.com",
        D,
        2,
        PRIV,
        "US",
    ),
    _source(
        "breaking-defense",
        "Breaking Defense",
        "https://breakingdefense.com/feed/",
        "https://breakingdefense.com",
        D,
        2,
        PRIV,
        "US",
    ),
    _source(
        "the-war-zone",
        "The War Zone",
        "https://www.twz.com/feed",
        "https://www.twz.com",
        D,
        2,
        PRIV,
        "US",
    ),
    _source(
        "bleepingcomputer",
        "BleepingComputer",
        "https://www.bleepingcomputer.com/feed/",
        "https://www.bleepingcomputer.com",
        C,
        2,
        PRIV,
        "US",
    ),
    _source(
        "the-record",
        "The Record",
        "https://therecord.media/feed",
        "https://therecord.media",
        C,
        2,
        PRIV,
        "US",
    ),
    # Added from worldmonitor's list; each feed read live on 2026-09-27 before inclusion.
    _source(
        "pbs",
        "PBS NewsHour",
        "https://www.pbs.org/newshour/feeds/rss/headlines",
        "https://www.pbs.org/newshour",
        W,
        1,
        PUB,
        "US",
    ),
    _source(
        "abc-au",
        "ABC News (Australia)",
        "https://www.abc.net.au/news/feed/2942460/rss.xml",
        "https://www.abc.net.au/news",
        W,
        1,
        PUB,
        "AU",
    ),
    _source(
        "cna",
        "CNA",
        "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
        "https://www.channelnewsasia.com",
        W,
        2,
        STATE,
        "SG",
    ),
    _source(
        "rfi-africa",
        "RFI Africa",
        "https://www.rfi.fr/en/africa/rss",
        "https://www.rfi.fr/en/africa",
        R,
        1,
        PUB,
        "FR",
    ),
    _source(
        "iaea",
        "IAEA",
        "https://www.iaea.org/feeds/topnews",
        "https://www.iaea.org",
        W,
        1,
        IGO,
        None,
    ),
    _source(
        "foreign-policy",
        "Foreign Policy",
        "https://foreignpolicy.com/feed/",
        "https://foreignpolicy.com",
        W,
        2,
        PRIV,
        "US",
    ),
    _source(
        "war-on-the-rocks",
        "War on the Rocks",
        "https://warontherocks.com/feed",
        "https://warontherocks.com",
        D,
        2,
        PRIV,
        "US",
    ),
    _source(
        "jamestown",
        "Jamestown Foundation",
        "https://jamestown.org/feed/",
        "https://jamestown.org",
        D,
        2,
        PRIV,
        "US",
    ),
    _source(
        "ynetnews",
        "Ynetnews",
        "https://www.ynetnews.com/Integration/StoryRss3089.xml",
        "https://www.ynetnews.com",
        R,
        2,
        PRIV,
        "IL",
    ),
    _source(
        "syria-direct",
        "Syria Direct",
        "https://syriadirect.org/feed/",
        "https://syriadirect.org",
        R,
        2,
        PRIV,
        "JO",
    ),
    _source(
        "egypt-independent",
        "Egypt Independent",
        "https://www.egyptindependent.com/feed/",
        "https://www.egyptindependent.com",
        R,
        2,
        PRIV,
        "EG",
    ),
    _source(
        "libya-herald",
        "Libya Herald",
        "https://libyaherald.com/rss.xml",
        "https://libyaherald.com",
        R,
        2,
        PRIV,
        "LY",
    ),
    _source(
        "irna",
        "IRNA",
        "https://en.irna.ir/rss",
        "https://en.irna.ir",
        R,
        3,
        STATE,
        "IR",
    ),
    _source(
        "moscow-times",
        "The Moscow Times",
        "https://www.themoscowtimes.com/rss/news",
        "https://www.themoscowtimes.com",
        R,
        2,
        PRIV,
        "NL",
    ),
    _source(
        "civil-ge",
        "Civil.ge",
        "https://civil.ge/feed/",
        "https://civil.ge",
        R,
        2,
        PRIV,
        "GE",
    ),
    _source(
        "oc-media",
        "OC Media",
        "https://oc-media.org/feed/",
        "https://oc-media.org",
        R,
        2,
        PRIV,
        "GE",
    ),
    _source(
        "balkan-insight",
        "Balkan Insight",
        "https://balkaninsight.com/feed/",
        "https://balkaninsight.com",
        R,
        2,
        PRIV,
        "RS",
    ),
    _source(
        "err-news",
        "ERR News",
        "https://news.err.ee/rss",
        "https://news.err.ee",
        R,
        1,
        PUB,
        "EE",
    ),
    _source(
        "lrt",
        "LRT English",
        "https://www.lrt.lt/en/news-in-english?rss",
        "https://www.lrt.lt/en/news-in-english",
        R,
        1,
        PUB,
        "LT",
    ),
    _source(
        "lsm",
        "LSM English",
        "https://eng.lsm.lv/rss/",
        "https://eng.lsm.lv",
        R,
        1,
        PUB,
        "LV",
    ),
    _source(
        "yle",
        "Yle News",
        "https://yle.fi/rss/news",
        "https://yle.fi/news",
        R,
        1,
        PUB,
        "FI",
    ),
    _source(
        "the-diplomat",
        "The Diplomat",
        "https://thediplomat.com/feed/",
        "https://thediplomat.com",
        R,
        2,
        PRIV,
        "US",
    ),
    _source(
        "japan-today",
        "Japan Today",
        "https://japantoday.com/feed/atom",
        "https://japantoday.com",
        R,
        2,
        PRIV,
        "JP",
    ),
    _source(
        "the-hindu",
        "The Hindu",
        "https://www.thehindu.com/news/national/feeder/default.rss",
        "https://www.thehindu.com",
        R,
        2,
        PRIV,
        "IN",
    ),
    _source(
        "dawn",
        "Dawn",
        "https://www.dawn.com/feeds/home/",
        "https://www.dawn.com",
        R,
        2,
        PRIV,
        "PK",
    ),
    _source(
        "rappler",
        "Rappler",
        "https://www.rappler.com/feed/",
        "https://www.rappler.com",
        R,
        2,
        PRIV,
        "PH",
    ),
    _source(
        "times-central-asia",
        "The Times of Central Asia",
        "https://timesca.com/feed/",
        "https://timesca.com",
        R,
        2,
        PRIV,
        "KZ",
    ),
    _source(
        "premium-times",
        "Premium Times",
        "https://www.premiumtimesng.com/feed",
        "https://www.premiumtimesng.com",
        R,
        2,
        PRIV,
        "NG",
    ),
    _source(
        "radio-tamazuj",
        "Radio Tamazuj",
        "https://www.radiotamazuj.org/en/feed",
        "https://www.radiotamazuj.org",
        R,
        2,
        PRIV,
        "NL",
    ),
    _source(
        "dabanga",
        "Dabanga",
        "https://www.dabangasudan.org/en/feed",
        "https://www.dabangasudan.org",
        R,
        2,
        PRIV,
        "NL",
    ),
    _source(
        "mexico-news-daily",
        "Mexico News Daily",
        "https://mexiconewsdaily.com/feed/",
        "https://mexiconewsdaily.com",
        R,
        2,
        PRIV,
        "MX",
    ),
    _source(
        "insight-crime",
        "InSight Crime",
        "https://insightcrime.org/feed/",
        "https://insightcrime.org",
        R,
        2,
        PRIV,
        "CO",
    ),
    _source(
        "caracas-chronicles",
        "Caracas Chronicles",
        "https://www.caracaschronicles.com/feed/",
        "https://www.caracaschronicles.com",
        R,
        2,
        PRIV,
        "VE",
    ),
)
