"""country signal snapshots

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 19:23:45.244127
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_signal_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("iso2", sa.String(length=2), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_country_signal_snapshots")),
    )
    with op.batch_alter_table("country_signal_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_country_signal_snapshots_iso2_taken_at", ["iso2", "taken_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_country_signal_snapshots_taken_at"), ["taken_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("country_signal_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_country_signal_snapshots_taken_at"))
        batch_op.drop_index("ix_country_signal_snapshots_iso2_taken_at")

    op.drop_table("country_signal_snapshots")
    # ### end Alembic commands ###
