"""assistant settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 21:42:37.157295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_settings",
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("api_key", sa.String(length=500), nullable=True),
        sa.Column("api_base", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("owner_id", name=op.f("pk_assistant_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assistant_settings")
    # ### end Alembic commands ###
