"""llm usage and embedding model

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 22:10:33.343198
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_usage")),
    )
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.create_index("ix_llm_usage_owner_at", ["owner_id", "at"], unique=False)

    with op.batch_alter_table("assistant_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedding_model", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assistant_settings", schema=None) as batch_op:
        batch_op.drop_column("embedding_model")
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_usage_owner_at")

    op.drop_table("llm_usage")
    # ### end Alembic commands ###
